### ISSUE TITLE
No calendars private account

### ISSUE THREAD

**Issue by jepajo** [RogerSelwyn/MS365-Calendar#54]
Thank you for this integration. When i use the calendar integration with a private account it doesnt pick up any calendars. I dont have any problems with mail or todo.

**Comment by RogerSelwyn** [comment]
Sorry I don’t know what a private account is. Is that a personal account. 

Are there any errors in the logs?

**Comment by jepajo** [comment]
Sorry. Personal account it is. Checking the logs when im at home.

**Comment by jepajo** [comment]
Logger: homeassistant.components.calendar
Källa: helpers/entity_platform.py:366
integration: Kalender (dokumentation, ärenden)
Inträffade först: 15:50:17 (1 händelser)
Senast loggade: 15:50:17

Error while setting up ms365_calendar platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ms365_calendar/calendar.py", line 17, in async_setup_entry
    return await async_integration_setup_entry(hass, entry, async_add_entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ms365_calendar/integration/calendar_integration.py", line 107, in async_integration_setup_entry
    await async_scan_for_calendars(hass, entry)
  File "/config/custom_components/ms365_calendar/integration/calendar_integration.py", line 763, in async_scan_for_calendars
    calendars = await hass.async_add_executor_job(schedule.list_calendars)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/O365/calendar.py", line 1933, in list_calendars
    response = self.con.get(url, params=params or None)
  File "/usr/local/lib/python3.13/site-packages/O365/connection.py", line 898, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/O365/connection.py", line 887, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/O365/connection.py", line 848, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message),
                    response=response) from None
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/calendars | Error Message: Access is denied. Check credentials and try again.

**Comment by jepajo** [comment]
Logger: O365.connection
Källa: /usr/local/lib/python3.13/site-packages/O365/connection.py:838
Inträffade först: 15:50:17 (1 händelser)
Senast loggade: 15:50:17

Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/calendars | Error Message: Access is denied. Check credentials and try again. | Error Code:

**Comment by jepajo** [comment]
It works now when i only Enable update services instead for also Enable read only basic calendar...

**Comment by RogerSelwyn** [comment]
Basic calendar does not support updates.

**Comment by jepajo** [comment]
Sometimes it helps just asking questions...
